"""
Alter company profile table (added staff column), staff model delete migration.
Generated by Django 4.2.3 on 2023-07-19 10:48
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Creates django migration that writes data to the database."""

    dependencies = [
        ('core', '0003_alter_staff_range_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='staff',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
