# Generated by Django 4.2.3 on 2023-10-10 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_create_default_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'permissions': [('apply_to_vacancy', 'Allows apply to any vacancy')]},
        ),
    ]
