"""
Renamed field in the Address table, removed fields from Company table to the CompanyProfile table.
Generated by Django 4.2.3 on 2023-07-19 19:58
"""

import core.models.company
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Creates django migration that writes data to the database."""

    dependencies = [
        ('core', '0009_vacancy_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='street_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo_link',
        ),
        migrations.RemoveField(
            model_name='company_profile',
            name='staff',
        ),
        migrations.AddField(
            model_name='company',
            name='staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='address',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='company_profiles',
                related_query_name='company_profile',
                to='core.address',
            ),
        ),
        migrations.AddField(
            model_name='company_profile',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company_profile',
            name='logo',
            field=models.ImageField(null=True, upload_to=core.models.company.company_directory_path),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='github_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='linkedin_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company_profile',
            name='twitter_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
