# Generated by Django 4.2.3 on 2023-10-10 13:27

import core.models.response
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0009_add_apply_vacancy_permission_for_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='summary_link',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='response',
            name='cv',
            field=models.FileField(null=True, upload_to=core.models.response.response_directory_path),
        ),
    ]
