"""
Alter length of field name in Country table and validators to attachment field Vacancy table.
Generated by Django 4.2.3 on 2023-07-20 11:15
"""

import core.models.vacancy
from django.db import migrations, models


class Migration(migrations.Migration):
    """Creates django migration that writes data to the database."""

    dependencies = [
        ('core', '0010_rename_name_address_street_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='attachment',
            field=models.FileField(null=True, upload_to=core.models.vacancy.vacancy_directory_path),
        ),
    ]
