# Generated by Django 4.2.3 on 2023-10-24 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_populate_responce_statuses_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='office_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='company_profile',
                to='core.address',
            ),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='company_profile',
                serialize=False,
                to='core.company',
            ),
        ),
    ]
