"""
Renamed 8 tables.
Generated by Django 4.2.3 on 2023-07-21 13:48
"""

from django.db import migrations


class Migration(migrations.Migration):
    """Creates django migration that writes data to the database."""

    dependencies = [
        ('core', '0013_remove_company_company_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business_area',
            new_name='BusinessArea',
        ),
        migrations.RenameModel(
            old_name='Employment_format',
            new_name='EmploymentFormat',
        ),
        migrations.RenameModel(
            old_name='Language_level',
            new_name='LanguageLevel',
        ),
        migrations.RenameModel(
            old_name='Response_status',
            new_name='ResponseStatus',
        ),
        migrations.RenameModel(
            old_name='Users_languages',
            new_name='UsersLanguages',
        ),
        migrations.RenameModel(
            old_name='Users_profile',
            new_name='UsersProfile',
        ),
        migrations.RenameModel(
            old_name='Work_format',
            new_name='WorkFormat',
        ),
        migrations.RenameModel(
            old_name='Work_status',
            new_name='WorkStatus',
        ),
    ]
