"""
Renamed CompanyProfile table.
Generated by Django 4.2.3 on 2023-07-21 13:51
"""

from django.db import migrations


class Migration(migrations.Migration):
    """Creates django migration that writes data to the database."""

    dependencies = [
        ('core', '0014_rename_business_area_businessarea_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company_Profile',
            new_name='CompanyProfile',
        ),
    ]
